// default package
// Generated 01.04.2015 15:28:33 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "oculusdb")
public class Doctor implements java.io.Serializable {

	private Integer doctorId;
	private Calendar calendar;
	private Doctor doctor;
	private User user;
	private Set<Doctor> doctors = new HashSet<Doctor>(0);
	private Set<Queue> queues = new HashSet<Queue>(0);
	private Set<Diagnosis> diagnosises = new HashSet<Diagnosis>(0);
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Doctor() {
	}

	public Doctor(Calendar calendar) {
		this.calendar = calendar;
	}

	public Doctor(Calendar calendar, Doctor doctor, User user,
			Set<Doctor> doctors, Set<Queue> queues, Set<Diagnosis> diagnosises,
			Set<Patient> patients) {
		this.calendar = calendar;
		this.doctor = doctor;
		this.user = user;
		this.doctors = doctors;
		this.queues = queues;
		this.diagnosises = diagnosises;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doctorId", unique = true, nullable = false)
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "calendarId", nullable = false)
	public Calendar getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Calendar calendar) {
		this.calendar = calendar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctorIdSubstitute")
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Queue> getQueues() {
		return this.queues;
	}

	public void setQueues(Set<Queue> queues) {
		this.queues = queues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Diagnosis> getDiagnosises() {
		return this.diagnosises;
	}

	public void setDiagnosises(Set<Diagnosis> diagnosises) {
		this.diagnosises = diagnosises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
