// default package
// Generated 01.04.2015 15:28:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Examinationprotocolservicecode generated by hbm2java
 */
@Entity
@Table(name = "examinationprotocolservicecode", catalog = "oculusdb")
public class Examinationprotocolservicecode implements java.io.Serializable {

	private Integer examinationProtocolServiceCodeId;
	private Examinationprotocol examinationprotocol;
	private Servicecode servicecode;
	private String insuranceCarrier;

	public Examinationprotocolservicecode() {
	}

	public Examinationprotocolservicecode(
			Examinationprotocol examinationprotocol, Servicecode servicecode,
			String insuranceCarrier) {
		this.examinationprotocol = examinationprotocol;
		this.servicecode = servicecode;
		this.insuranceCarrier = insuranceCarrier;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "examinationProtocolServiceCodeId", unique = true, nullable = false)
	public Integer getExaminationProtocolServiceCodeId() {
		return this.examinationProtocolServiceCodeId;
	}

	public void setExaminationProtocolServiceCodeId(
			Integer examinationProtocolServiceCodeId) {
		this.examinationProtocolServiceCodeId = examinationProtocolServiceCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinationProtocolId")
	public Examinationprotocol getExaminationprotocol() {
		return this.examinationprotocol;
	}

	public void setExaminationprotocol(Examinationprotocol examinationprotocol) {
		this.examinationprotocol = examinationprotocol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceCodeId")
	public Servicecode getServicecode() {
		return this.servicecode;
	}

	public void setServicecode(Servicecode servicecode) {
		this.servicecode = servicecode;
	}

	@Column(name = "insuranceCarrier")
	public String getInsuranceCarrier() {
		return this.insuranceCarrier;
	}

	public void setInsuranceCarrier(String insuranceCarrier) {
		this.insuranceCarrier = insuranceCarrier;
	}

}
