// default package
// Generated 14.04.2015 20:32:57 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medicine generated by hbm2java
 */
@Entity
@Table(name = "medicine", catalog = "oculusdb")
public class Medicine implements java.io.Serializable {

	private Integer medicineId;
	private Diagnosis diagnosis;
	private String name;
	private String dose;
	private Set<Prescriptionentry> prescriptionentries = new HashSet<Prescriptionentry>(
			0);

	public Medicine() {
	}

	public Medicine(Diagnosis diagnosis, String name) {
		this.diagnosis = diagnosis;
		this.name = name;
	}

	public Medicine(Diagnosis diagnosis, String name, String dose,
			Set<Prescriptionentry> prescriptionentries) {
		this.diagnosis = diagnosis;
		this.name = name;
		this.dose = dose;
		this.prescriptionentries = prescriptionentries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "medicineId", unique = true, nullable = false)
	public Integer getMedicineId() {
		return this.medicineId;
	}

	public void setMedicineId(Integer medicineId) {
		this.medicineId = medicineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diagnosisId", nullable = false)
	public Diagnosis getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "dose")
	public String getDose() {
		return this.dose;
	}

	public void setDose(String dose) {
		this.dose = dose;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicine")
	public Set<Prescriptionentry> getPrescriptionentries() {
		return this.prescriptionentries;
	}

	public void setPrescriptionentries(
			Set<Prescriptionentry> prescriptionentries) {
		this.prescriptionentries = prescriptionentries;
	}

}
