// default package
// Generated 14.04.2015 20:32:57 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orthoptist generated by hbm2java
 */
@Entity
@Table(name = "orthoptist", catalog = "oculusdb")
public class Orthoptist implements java.io.Serializable {

	private Integer orthoptistId;
	private Calendar calendar;
	private User user;
	private Set<Queue> queues = new HashSet<Queue>(0);

	public Orthoptist() {
	}

	public Orthoptist(Calendar calendar) {
		this.calendar = calendar;
	}

	public Orthoptist(Calendar calendar, User user, Set<Queue> queues) {
		this.calendar = calendar;
		this.user = user;
		this.queues = queues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orthoptistId", unique = true, nullable = false)
	public Integer getOrthoptistId() {
		return this.orthoptistId;
	}

	public void setOrthoptistId(Integer orthoptistId) {
		this.orthoptistId = orthoptistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "calendarId", nullable = false)
	public Calendar getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Calendar calendar) {
		this.calendar = calendar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orthoptist")
	public Set<Queue> getQueues() {
		return this.queues;
	}

	public void setQueues(Set<Queue> queues) {
		this.queues = queues;
	}

}
