// default package
// Generated 14.04.2015 20:32:57 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prescription generated by hbm2java
 */
@Entity
@Table(name = "prescription", catalog = "oculusdb")
public class Prescription implements java.io.Serializable {

	private Integer prescriptionId;
	private Patient patient;
	private Date issueDate;
	private Set<Prescriptionentry> prescriptionentries = new HashSet<Prescriptionentry>(
			0);

	public Prescription() {
	}

	public Prescription(Patient patient, Date issueDate,
			Set<Prescriptionentry> prescriptionentries) {
		this.patient = patient;
		this.issueDate = issueDate;
		this.prescriptionentries = prescriptionentries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prescriptionId", unique = true, nullable = false)
	public Integer getPrescriptionId() {
		return this.prescriptionId;
	}

	public void setPrescriptionId(Integer prescriptionId) {
		this.prescriptionId = prescriptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patientId")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issueDate", length = 19)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prescription")
	public Set<Prescriptionentry> getPrescriptionentries() {
		return this.prescriptionentries;
	}

	public void setPrescriptionentries(
			Set<Prescriptionentry> prescriptionentries) {
		this.prescriptionentries = prescriptionentries;
	}

}
