// default package
// Generated 01.04.2015 15:28:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Receptionist generated by hbm2java
 */
@Entity
@Table(name = "receptionist", catalog = "oculusdb")
public class Receptionist implements java.io.Serializable {

	private Integer receptionistId;
	private User user;

	public Receptionist() {
	}

	public Receptionist(User user) {
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "receptionistId", unique = true, nullable = false)
	public Integer getReceptionistId() {
		return this.receptionistId;
	}

	public void setReceptionistId(Integer receptionistId) {
		this.receptionistId = receptionistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
