// default package
// Generated 01.04.2015 15:28:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userpermission generated by hbm2java
 */
@Entity
@Table(name = "userpermission", catalog = "oculusdb")
public class Userpermission implements java.io.Serializable {

	private Integer userPermissionId;
	private Permission permission;
	private User user;
	private Usergroup usergroup;

	public Userpermission() {
	}

	public Userpermission(Permission permission, User user, Usergroup usergroup) {
		this.permission = permission;
		this.user = user;
		this.usergroup = usergroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userPermissionId", unique = true, nullable = false)
	public Integer getUserPermissionId() {
		return this.userPermissionId;
	}

	public void setUserPermissionId(Integer userPermissionId) {
		this.userPermissionId = userPermissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permissionId")
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userGroupId")
	public Usergroup getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(Usergroup usergroup) {
		this.usergroup = usergroup;
	}

}
