// default package
// Generated 14.04.2015 20:32:57 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Visualaid generated by hbm2java
 */
@Entity
@Table(name = "visualaid", catalog = "oculusdb")
public class Visualaid implements java.io.Serializable {

	private Integer visualAidId;
	private Diagnosis diagnosis;

	public Visualaid() {
	}

	public Visualaid(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "visualAidId", unique = true, nullable = false)
	public Integer getVisualAidId() {
		return this.visualAidId;
	}

	public void setVisualAidId(Integer visualAidId) {
		this.visualAidId = visualAidId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diagnosisId")
	public Diagnosis getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

}
