package at.itb13.oculus.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendarevent generated by hbm2java
 */
@Entity
@Table(name = "calendarevent", catalog = "oculusdb")
public class Calendarevent implements java.io.Serializable {

	private Integer calendarEventId;
	private Calendar calendar;
	private Eventtype eventtype;
	private Patient patient;
	private Date eventStart;
	private Date eventEnd;
	private String description;
	private String patientName;
	private boolean isOpen;

	public Calendarevent() {
	}

	public Calendarevent(Calendar calendar, Eventtype eventtype,
			Date eventStart, Date eventEnd, boolean isOpen) {
		this.calendar = calendar;
		this.eventtype = eventtype;
		this.eventStart = eventStart;
		this.eventEnd = eventEnd;
		this.isOpen = isOpen;
	}

	public Calendarevent(Calendar calendar, Eventtype eventtype,
			Patient patient, Date eventStart, Date eventEnd,
			String description, String patientName, boolean isOpen) {
		this.calendar = calendar;
		this.eventtype = eventtype;
		this.patient = patient;
		this.eventStart = eventStart;
		this.eventEnd = eventEnd;
		this.description = description;
		this.patientName = patientName;
		this.isOpen = isOpen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "calendarEventId", unique = true, nullable = false)
	public Integer getCalendarEventId() {
		return this.calendarEventId;
	}

	public void setCalendarEventId(Integer calendarEventId) {
		this.calendarEventId = calendarEventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "calendarId", nullable = false)
	public Calendar getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Calendar calendar) {
		this.calendar = calendar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventTypeId", nullable = false)
	public Eventtype getEventtype() {
		return this.eventtype;
	}

	public void setEventtype(Eventtype eventtype) {
		this.eventtype = eventtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patientId")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventStart", nullable = false, length = 19)
	public Date getEventStart() {
		return this.eventStart;
	}

	public void setEventStart(Date eventStart) {
		this.eventStart = eventStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventEnd", nullable = false, length = 19)
	public Date getEventEnd() {
		return this.eventEnd;
	}

	public void setEventEnd(Date eventEnd) {
		this.eventEnd = eventEnd;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "patientName", length = 100)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "isOpen", nullable = false)
	public boolean isIsOpen() {
		return this.isOpen;
	}

	public void setIsOpen(boolean isOpen) {
		this.isOpen = isOpen;
	}

}
