package at.itb13.oculus.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

import javassist.NotFoundException;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendar", catalog = "oculusdb")
public class Calendar implements java.io.Serializable {

	private static final Logger _logger = LogManager.getLogger(Calendar.class
			.getName());
	private static final long serialVersionUID = 1L;
	private Integer _calendarId;
	private String _title;
	private Set<Doctor> _doctors = new HashSet<Doctor>(0);
	private Set<Orthoptist> _orthoptists = new HashSet<Orthoptist>(0);
	private Set<CalendarEvent> _calendarevents = new HashSet<CalendarEvent>(0);
	private Set<Workinghours> _workinghours = new HashSet<Workinghours>(0);

	public Calendar() {
	}

	public Calendar(String title, Set<Doctor> doctors,
			Set<Orthoptist> orthoptists, Set<CalendarEvent> calendarevents,
			Set<Workinghours> workinghourses) {
		_title = title;
		_doctors = doctors;
		_orthoptists = orthoptists;
		_calendarevents = calendarevents;
		_workinghours = workinghourses;
	}

	/**
	 * Creates a list of Calendar Event in a chosen timespan.
	 * 
	 * @param startDate
	 *            the start Date of the timespan.
	 * @param endDate
	 *            the end Date of the timespan.
	 * @return A list of CalendarEvent.
	 */
	public List<CalendarEvent> getCalendarEvents(Date startDate, Date endDate) {
		List<CalendarEvent> curEvents = new LinkedList<>();
		for (CalendarEvent c : _calendarevents) {
			if (c.isInTimespan(startDate, endDate)) {
				curEvents.add(c);
			}
		}
		return curEvents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "calendarId", unique = true, nullable = false)
	public Integer getCalendarId() {
		return _calendarId;
	}

	public void setCalendarId(Integer calendarId) {
		_calendarId = calendarId;
	}

	@Column(name = "title")
	public String getTitle() {
		return _title;
	}

	public void setTitle(String title) {
		_title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendar")
	public Set<Doctor> getDoctors() {
		return _doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		_doctors = doctors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendar")
	public Set<Orthoptist> getOrthoptists() {
		return _orthoptists;
	}

	public void setOrthoptists(Set<Orthoptist> orthoptists) {
		_orthoptists = orthoptists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendar")
	public Set<CalendarEvent> getCalendarevents() {
		return _calendarevents;
	}

	public void setCalendarevents(Set<CalendarEvent> calendarevents) {
		_calendarevents = calendarevents;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "calendars")
	public Set<Workinghours> getWorkinghourses() {
		return _workinghours;
	}

	public void setWorkinghourses(Set<Workinghours> workinghourses) {
		_workinghours = workinghourses;
	}

	// TODO getCalendarEvents

	/**
	 * Returns calendarevents in timespan
	 * 
	 * @return
	 */
	// public Set<CalendarEvent> getCalendarevents(Calendar cal, anfang ende) {
	// return this.calendarevents;
	// }
}
