package at.itb13.oculus.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Diagnosis generated by hbm2java
 */
@Entity
@Table(name = "diagnosis", catalog = "oculus_d")
public class Diagnosis implements java.io.Serializable {

	private static final Logger _logger = LogManager.getLogger(Diagnosis.class
			.getName());
	private static final long serialVersionUID = 1L;
	private Integer diagnosisId;
	private Doctor doctor;
	private String title;
	private String description;
	private Set<ExaminationProtocol> examinationprotocols = new HashSet<ExaminationProtocol>(
			0);
	private Set<VisualAid> visualaids = new HashSet<VisualAid>(0);
	private Set<WorkDisability> workdisabilities = new HashSet<WorkDisability>(
			0);
	private Set<Medicine> medicines = new HashSet<Medicine>(0);

	public Diagnosis() {
	}

	public Diagnosis(Doctor doctor, String title, String description,
			Set<ExaminationProtocol> examinationprotocols,
			Set<VisualAid> visualaids, Set<WorkDisability> workdisabilities,
			Set<Medicine> medicines) {
		this.doctor = doctor;
		this.title = title;
		this.description = description;
		this.examinationprotocols = examinationprotocols;
		this.visualaids = visualaids;
		this.workdisabilities = workdisabilities;
		this.medicines = medicines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "diagnosisId", unique = true, nullable = false)
	public Integer getDiagnosisId() {
		return this.diagnosisId;
	}

	public void setDiagnosisId(Integer diagnosisId) {
		this.diagnosisId = diagnosisId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctorId")
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosis")
	public Set<ExaminationProtocol> getExaminationprotocols() {
		return this.examinationprotocols;
	}

	public void setExaminationprotocols(
			Set<ExaminationProtocol> examinationprotocols) {
		this.examinationprotocols = examinationprotocols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosis")
	public Set<VisualAid> getVisualaids() {
		return this.visualaids;
	}

	public void setVisualaids(Set<VisualAid> visualaids) {
		this.visualaids = visualaids;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosis")
	public Set<WorkDisability> getWorkdisabilities() {
		return this.workdisabilities;
	}

	public void setWorkdisabilities(Set<WorkDisability> workdisabilities) {
		this.workdisabilities = workdisabilities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosis")
	public Set<Medicine> getMedicines() {
		return this.medicines;
	}

	public void setMedicines(Set<Medicine> medicines) {
		this.medicines = medicines;
	}

}
