package at.itb13.oculus.domain;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Examinationprotocolservicecode generated by hbm2java
 */
@Entity
@Table(name = "examinationprotocolservicecode", catalog = "oculusdb")
public class ExaminationProtocolServiceCode implements java.io.Serializable {

	private ExaminationProtocolServiceCodeID id;
	private ExaminationProtocol examinationprotocol;
	private InsuranceCarrier insurancecarrier;
	private ServiceCode servicecode;

	public ExaminationProtocolServiceCode() {
	}

	public ExaminationProtocolServiceCode(ExaminationProtocolServiceCodeID id,
			ExaminationProtocol examinationprotocol,
			InsuranceCarrier insurancecarrier, ServiceCode servicecode) {
		this.id = id;
		this.examinationprotocol = examinationprotocol;
		this.insurancecarrier = insurancecarrier;
		this.servicecode = servicecode;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "examinationProtocolId", column = @Column(name = "examinationProtocolId", nullable = false)),
			@AttributeOverride(name = "serviceCodeId", column = @Column(name = "serviceCodeId", nullable = false)),
			@AttributeOverride(name = "insuranceCarrierKey", column = @Column(name = "insuranceCarrierKey", nullable = false, length = 4)) })
	public ExaminationProtocolServiceCodeID getId() {
		return this.id;
	}

	public void setId(ExaminationProtocolServiceCodeID id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinationProtocolId", nullable = false, insertable = false, updatable = false)
	public ExaminationProtocol getExaminationprotocol() {
		return this.examinationprotocol;
	}

	public void setExaminationprotocol(ExaminationProtocol examinationprotocol) {
		this.examinationprotocol = examinationprotocol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "insuranceCarrierKey", nullable = false, insertable = false, updatable = false)
	public InsuranceCarrier getInsurancecarrier() {
		return this.insurancecarrier;
	}

	public void setInsurancecarrier(InsuranceCarrier insurancecarrier) {
		this.insurancecarrier = insurancecarrier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceCodeId", nullable = false, insertable = false, updatable = false)
	public ServiceCode getServicecode() {
		return this.servicecode;
	}

	public void setServicecode(ServiceCode servicecode) {
		this.servicecode = servicecode;
	}

}
