package at.itb13.oculus.domain;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Convert;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import at.itb13.oculus.domain.readonlyinterfaces.ExaminationProtocolRO;
import at.itb13.oculus.technicalServices.util.LocalDateTimePersistenceConverter;

/**
 * Examinationprotocol generated by hbm2java
 */
@Entity
@Table(name = "examinationprotocol", catalog = "oculus_d")
public class ExaminationProtocol implements java.io.Serializable, ExaminationProtocolRO {

	private static final Logger _logger = LogManager.getLogger(ExaminationProtocol.class
			.getName());
	private static final long serialVersionUID = 1L;
	private Integer examinationProtocolId;
	private Diagnosis diagnosis;
	private Patient patient;
	private User user;
	private LocalDateTime startProtocol;
	private LocalDateTime endProtocol;
	private String description;
	private Set<ExaminationResult> examinationresults = new HashSet<ExaminationResult>(
			0);
	private Set<ExaminationProtocolServiceCode> examinationprotocolservicecodes = new HashSet<ExaminationProtocolServiceCode>(
			0);
	private Set<ReferralLetter> referralletters = new HashSet<ReferralLetter>(0);

	public ExaminationProtocol() {
	}

	public ExaminationProtocol(
			Diagnosis diagnosis,
			Patient patient,
			User user,
			LocalDateTime startProtocol,
			LocalDateTime endProtocol,
			String description,
			Set<ExaminationResult> examinationresults,
			Set<ExaminationProtocolServiceCode> examinationprotocolservicecodes,
			Set<ReferralLetter> referralletters) {
		this.diagnosis = diagnosis;
		this.patient = patient;
		this.user = user;
		this.startProtocol = startProtocol;
		this.endProtocol = endProtocol;
		this.description = description;
		this.examinationresults = examinationresults;
		this.examinationprotocolservicecodes = examinationprotocolservicecodes;
		this.referralletters = referralletters;
	}
	
	/**
	 * Gives back a sorted Linked List<ExaminationProtocols>, the newest ExaminationProtocol is the first Element.
	 * 
	 * @param Set <ExaminationProtocol> examinationProtocols
	 * @return Linked List <ExaminationProtocol>
	 */
	@Transient
	public static List<ExaminationProtocol> sortExaminationProtocolsByStartDate(
			Set<ExaminationProtocol> examinationProtocols) {
			List<ExaminationProtocol> unsortedExaminationProtocols = new LinkedList<ExaminationProtocol>(examinationProtocols);
			List<ExaminationProtocol> sortedExaminationProtocols = new LinkedList<ExaminationProtocol>();
			ExaminationProtocol epMax = null;
			while (!unsortedExaminationProtocols.isEmpty()){
				epMax = unsortedExaminationProtocols.get(0);
				for (ExaminationProtocol ep:unsortedExaminationProtocols){
					if (epMax.getStartProtocol().isBefore(ep.getStartProtocol())){
						epMax = ep;
					}
				}
				sortedExaminationProtocols.add(epMax);
				unsortedExaminationProtocols.remove(epMax);
			}
			
//			Collections.sort(sortedExaminationProtocols, new ExaminationProtocolComparator());
		return sortedExaminationProtocols;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "examinationProtocolId", unique = true, nullable = false)
	public Integer getExaminationProtocolId() {
		return this.examinationProtocolId;
	}

	public void setExaminationProtocolId(Integer examinationProtocolId) {
		this.examinationProtocolId = examinationProtocolId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diagnosisId")
	public Diagnosis getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patientId")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Convert(converter = LocalDateTimePersistenceConverter.class)
	@Column(name = "startProtocol", length = 19)
	public LocalDateTime getStartProtocol() {
		return this.startProtocol;
	}

	public void setStartProtocol(LocalDateTime startProtocol) {
		this.startProtocol = startProtocol;
	}

	@Convert(converter = LocalDateTimePersistenceConverter.class)
	@Column(name = "endProtocol", length = 19)
	public LocalDateTime getEndProtocol() {
		return this.endProtocol;
	}

	public void setEndProtocol(LocalDateTime endProtocol) {
		this.endProtocol = endProtocol;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examinationprotocol")
	public Set<ExaminationResult> getExaminationResults() {
		return this.examinationresults;
	}

	public void setExaminationResults(Set<ExaminationResult> examinationResults) {
		this.examinationresults = examinationResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examinationprotocol")
	public Set<ExaminationProtocolServiceCode> getExaminationProtocolServiceCodes() {
		return this.examinationprotocolservicecodes;
	}

	public void setExaminationProtocolServiceCodes(
			Set<ExaminationProtocolServiceCode> examinationProtocolServiceCodes) {
		this.examinationprotocolservicecodes = examinationProtocolServiceCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examinationprotocol")
	public Set<ReferralLetter> getReferralLetters() {
		return this.referralletters;
	}

	public void setReferralLetters(Set<ReferralLetter> referralLetters) {
		this.referralletters = referralLetters;
	}

}
