package at.itb13.oculus.domain;

import java.time.LocalDateTime;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Convert;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import at.itb13.oculus.technicalServices.util.LocalDateTimePersistenceConverter;

/**
 * Examinationresult generated by hbm2java
 */
@Entity
@Table(name = "examinationresult", catalog = "oculusdb")
public class ExaminationResult implements java.io.Serializable {

	private static final Logger _logger = LogManager.getLogger(ExaminationResult.class
			.getName());
	private static final long serialVersionUID = 1L;
	private Integer examinationResultId;
	private ExaminationProtocol examinationprotocol;
	private User user;
	private String result;
	private LocalDateTime createDate;
	private String device;
	private byte[] deviceData;

	public ExaminationResult() {
	}

	public ExaminationResult(ExaminationProtocol examinationprotocol,
			User user, String result, LocalDateTime createDate, String device,
			byte[] deviceData) {
		this.examinationprotocol = examinationprotocol;
		this.user = user;
		this.result = result;
		this.createDate = createDate;
		this.device = device;
		this.deviceData = deviceData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "examinationResultId", unique = true, nullable = false)
	public Integer getExaminationResultId() {
		return this.examinationResultId;
	}

	public void setExaminationResultId(Integer examinationResultId) {
		this.examinationResultId = examinationResultId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinationProtocolId")
	public ExaminationProtocol getExaminationprotocol() {
		return this.examinationprotocol;
	}

	public void setExaminationprotocol(ExaminationProtocol examinationprotocol) {
		this.examinationprotocol = examinationprotocol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "result", length = 65535)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Convert(converter = LocalDateTimePersistenceConverter.class)
	@Column(name = "createDate", length = 19)
	public LocalDateTime getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(LocalDateTime createDate) {
		this.createDate = createDate;
	}

	@Column(name = "device")
	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	@Column(name = "deviceData")
	public byte[] getDeviceData() {
		return this.deviceData;
	}

	public void setDeviceData(byte[] deviceData) {
		this.deviceData = deviceData;
	}

}
