package at.itb13.oculus.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Insurancecarrier generated by hbm2java
 */
@Entity
@Table(name = "insurancecarrier", catalog = "oculusdb")
public class InsuranceCarrier implements java.io.Serializable {

	private static final Logger _logger = LogManager.getLogger(InsuranceCarrier.class
			.getName());
	private static final long serialVersionUID = 1L;
	private String insuranceCarrierKey;
	private String name;
	private Set<ExaminationProtocolServiceCode> examinationprotocolservicecodes = new HashSet<ExaminationProtocolServiceCode>(
			0);

	public InsuranceCarrier() {
	}

	public InsuranceCarrier(String insuranceCarrierKey, String name) {
		this.insuranceCarrierKey = insuranceCarrierKey;
		this.name = name;
	}

	public InsuranceCarrier(String insuranceCarrierKey, String name,
			Set<ExaminationProtocolServiceCode> examinationprotocolservicecodes) {
		this.insuranceCarrierKey = insuranceCarrierKey;
		this.name = name;
		this.examinationprotocolservicecodes = examinationprotocolservicecodes;
	}

	@Id
	@Column(name = "insuranceCarrierKey", unique = true, nullable = false, length = 4)
	public String getInsuranceCarrierKey() {
		return this.insuranceCarrierKey;
	}

	public void setInsuranceCarrierKey(String insuranceCarrierKey) {
		this.insuranceCarrierKey = insuranceCarrierKey;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "insurancecarrier")
	public Set<ExaminationProtocolServiceCode> getExaminationprotocolservicecodes() {
		return this.examinationprotocolservicecodes;
	}

	public void setExaminationprotocolservicecodes(
			Set<ExaminationProtocolServiceCode> examinationprotocolservicecodes) {
		this.examinationprotocolservicecodes = examinationprotocolservicecodes;
	}

}
