// default package
// Generated 03.04.2015 16:43:15 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Insurancecarrier generated by hbm2java
 */
@Entity
@Table(name = "insurancecarrier", catalog = "oculusdb")
public class Insurancecarrier implements java.io.Serializable {

	private String insuranceCarrierKey;
	private String name;
	private Set<Examinationprotocolservicecode> examinationprotocolservicecodes = new HashSet<Examinationprotocolservicecode>(
			0);

	public Insurancecarrier() {
	}

	public Insurancecarrier(String insuranceCarrierKey, String name) {
		this.insuranceCarrierKey = insuranceCarrierKey;
		this.name = name;
	}

	public Insurancecarrier(String insuranceCarrierKey, String name,
			Set<Examinationprotocolservicecode> examinationprotocolservicecodes) {
		this.insuranceCarrierKey = insuranceCarrierKey;
		this.name = name;
		this.examinationprotocolservicecodes = examinationprotocolservicecodes;
	}

	@Id
	@Column(name = "insuranceCarrierKey", unique = true, nullable = false, length = 4)
	public String getInsuranceCarrierKey() {
		return this.insuranceCarrierKey;
	}

	public void setInsuranceCarrierKey(String insuranceCarrierKey) {
		this.insuranceCarrierKey = insuranceCarrierKey;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "insurancecarrier")
	public Set<Examinationprotocolservicecode> getExaminationprotocolservicecodes() {
		return this.examinationprotocolservicecodes;
	}

	public void setExaminationprotocolservicecodes(
			Set<Examinationprotocolservicecode> examinationprotocolservicecodes) {
		this.examinationprotocolservicecodes = examinationprotocolservicecodes;
	}

}
