package at.itb13.oculus.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orthoptist generated by hbm2java
 */
@Entity
@Table(name = "orthoptist", catalog = "oculusdb")
public class Orthoptist implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer orthoptistId;
	private Calendar calendar;
	private User user;
	private Queue _queue;

	public Orthoptist() {
	}

	public Orthoptist(Calendar calendar) {
		this.calendar = calendar;
	}

	public Orthoptist(Calendar calendar, User user) {
		this.calendar = calendar;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orthoptistId", unique = true, nullable = false)
	public Integer getOrthoptistId() {
		return this.orthoptistId;
	}

	public void setOrthoptistId(Integer orthoptistId) {
		this.orthoptistId = orthoptistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "calendarId", nullable = false)
	public Calendar getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Calendar calendar) {
		this.calendar = calendar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * @return the queue
	 */
	public Queue getQueue() {
		return _queue;
	}

	/**
	 * @param queue the queue to set
	 */
	public void setQueue(Queue queue) {
		_queue = queue; // TODO: CHECK IF queue.orthoptist id okay or maybe even remove setQueue()
	}
}
