package at.itb13.oculus.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prescriptionentry generated by hbm2java
 */
@Entity
@Table(name = "prescriptionentry", catalog = "oculus_d")
public class PrescriptionEntry implements java.io.Serializable {

	private Integer prescriptionEntryId;
	private Medicine medicine;
	private Prescription prescription;

	public PrescriptionEntry() {
	}

	public PrescriptionEntry(Medicine medicine, Prescription prescription) {
		this.medicine = medicine;
		this.prescription = prescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "prescriptionEntryId", unique = true, nullable = false)
	public Integer getPrescriptionEntryId() {
		return this.prescriptionEntryId;
	}

	public void setPrescriptionEntryId(Integer prescriptionEntryId) {
		this.prescriptionEntryId = prescriptionEntryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicineId")
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prescriptionId")
	public Prescription getPrescription() {
		return this.prescription;
	}

	public void setPrescription(Prescription prescription) {
		this.prescription = prescription;
	}

}
