package at.itb13.oculus.domain;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Receptionist generated by hbm2java
 */
@Entity
@Table(name = "receptionist", catalog = "oculus_d")
public class Receptionist implements java.io.Serializable {

	private static final Logger _logger = LogManager.getLogger(Receptionist.class
			.getName());
	private static final long serialVersionUID = 1L;
	private Integer receptionistId;
	private User user;

	public Receptionist() {
	}

	public Receptionist(User user) {
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "receptionistId", unique = true, nullable = false)
	public Integer getReceptionistId() {
		return this.receptionistId;
	}

	public void setReceptionistId(Integer receptionistId) {
		this.receptionistId = receptionistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
