// default package
// Generated 03.04.2015 15:26:50 by Hibernate Tools 4.3.1

/**
 * Receptionist generated by hbm2java
 */
public class Receptionist implements java.io.Serializable {

	private Integer receptionistId;
	private User user;

	public Receptionist() {
	}

	public Receptionist(User user) {
		this.user = user;
	}

	public Integer getReceptionistId() {
		return this.receptionistId;
	}

	public void setReceptionistId(Integer receptionistId) {
		this.receptionistId = receptionistId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
