package at.itb13.oculus.domain;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Referralletter generated by hbm2java
 */
@Entity
@Table(name = "referralletter", catalog = "oculusdb")
public class ReferralLetter implements java.io.Serializable {

	private static final Logger _logger = LogManager.getLogger(ReferralLetter.class
			.getName());
	private static final long serialVersionUID = 1L;
	private Integer referralLetterId;
	private ExaminationProtocol examinationprotocol;
	private Patient patient;
	private String externalInstitute;
	private String reason;

	public ReferralLetter() {
	}

	public ReferralLetter(String externalInstitute, String reason) {
		this.externalInstitute = externalInstitute;
		this.reason = reason;
	}

	public ReferralLetter(ExaminationProtocol examinationprotocol,
			Patient patient, String externalInstitute, String reason) {
		this.examinationprotocol = examinationprotocol;
		this.patient = patient;
		this.externalInstitute = externalInstitute;
		this.reason = reason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "referralLetterId", unique = true, nullable = false)
	public Integer getReferralLetterId() {
		return this.referralLetterId;
	}

	public void setReferralLetterId(Integer referralLetterId) {
		this.referralLetterId = referralLetterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinationProtocolId")
	public ExaminationProtocol getExaminationprotocol() {
		return this.examinationprotocol;
	}

	public void setExaminationprotocol(ExaminationProtocol examinationprotocol) {
		this.examinationprotocol = examinationprotocol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patientId")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "externalInstitute", nullable = false, length = 65535)
	public String getExternalInstitute() {
		return this.externalInstitute;
	}

	public void setExternalInstitute(String externalInstitute) {
		this.externalInstitute = externalInstitute;
	}

	@Column(name = "reason", nullable = false, length = 65535)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
