// default package
// Generated 03.04.2015 16:43:15 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userpermission generated by hbm2java
 */
@Entity
@Table(name = "userpermission", catalog = "oculusdb")
public class Userpermission implements java.io.Serializable {

	private UserpermissionId id;
	private Permission permission;
	private User user;
	private Usergroup usergroup;

	public Userpermission() {
	}

	public Userpermission(UserpermissionId id, Permission permission,
			User user, Usergroup usergroup) {
		this.id = id;
		this.permission = permission;
		this.user = user;
		this.usergroup = usergroup;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permissionId", column = @Column(name = "permissionId", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "userId", nullable = false)),
			@AttributeOverride(name = "userGroupId", column = @Column(name = "userGroupId", nullable = false)) })
	public UserpermissionId getId() {
		return this.id;
	}

	public void setId(UserpermissionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permissionId", nullable = false, insertable = false, updatable = false)
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userGroupId", nullable = false, insertable = false, updatable = false)
	public Usergroup getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(Usergroup usergroup) {
		this.usergroup = usergroup;
	}

}
