package at.itb13.oculus.domain;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserpermissionId generated by hbm2java
 */
@Embeddable
public class UserPermissionID implements java.io.Serializable {

	private int permissionId;
	private int userId;
	private int userGroupId;

	public UserPermissionID() {
	}

	public UserPermissionID(int permissionId, int userId, int userGroupId) {
		this.permissionId = permissionId;
		this.userId = userId;
		this.userGroupId = userGroupId;
	}

	@Column(name = "permissionId", nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "userGroupId", nullable = false)
	public int getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(int userGroupId) {
		this.userGroupId = userGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserPermissionID))
			return false;
		UserPermissionID castOther = (UserPermissionID) other;

		return (this.getPermissionId() == castOther.getPermissionId())
				&& (this.getUserId() == castOther.getUserId())
				&& (this.getUserGroupId() == castOther.getUserGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPermissionId();
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getUserGroupId();
		return result;
	}

}
