// default package
// Generated 03.04.2015 15:26:50 by Hibernate Tools 4.3.1

/**
 * Visualaid generated by hbm2java
 */
public class Visualaid implements java.io.Serializable {

	private Integer visualAidId;
	private Diagnosis diagnosis;

	public Visualaid() {
	}

	public Visualaid(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	public Integer getVisualAidId() {
		return this.visualAidId;
	}

	public void setVisualAidId(Integer visualAidId) {
		this.visualAidId = visualAidId;
	}

	public Diagnosis getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

}
