package at.itb13.oculus.domain;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Weekday generated by hbm2java
 */
@Entity
@Table(name = "weekday", catalog = "oculusdb")
public class Weekday implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String weekDayKey;
	private String name;
	private Set<Workinghours> workinghourses = new HashSet<Workinghours>(0);

	public Weekday() {
	}

	public Weekday(String weekDayKey, String name) {
		this.weekDayKey = weekDayKey;
		this.name = name;
	}

	public Weekday(String weekDayKey, String name,
			Set<Workinghours> workinghourses) {
		this.weekDayKey = weekDayKey;
		this.name = name;
		this.workinghourses = workinghourses;
	}

	@Id
	@Column(name = "weekDayKey", unique = true, nullable = false, length = 3)
	public String getWeekDayKey() {
		return this.weekDayKey;
	}

	public void setWeekDayKey(String weekDayKey) {
		this.weekDayKey = weekDayKey;
	}

	@Column(name = "name", nullable = false, length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weekday")
	public Set<Workinghours> getWorkinghourses() {
		return this.workinghourses;
	}

	public void setWorkinghourses(Set<Workinghours> workinghourses) {
		this.workinghourses = workinghourses;
	}

}
