package at.itb13.oculus.domain;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Workdisability generated by hbm2java
 */
@Entity
@Table(name = "workdisability", catalog = "oculusdb")
public class Workdisability implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer workDisabilityId;
	private Diagnosis diagnosis;
	private Date startDisability;
	private Date endDisability;
	private String reason;
	private Boolean bedRest;

	public Workdisability() {
	}

	public Workdisability(Diagnosis diagnosis, Date startDisability,
			Date endDisability, String reason, Boolean bedRest) {
		this.diagnosis = diagnosis;
		this.startDisability = startDisability;
		this.endDisability = endDisability;
		this.reason = reason;
		this.bedRest = bedRest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "workDisabilityId", unique = true, nullable = false)
	public Integer getWorkDisabilityId() {
		return this.workDisabilityId;
	}

	public void setWorkDisabilityId(Integer workDisabilityId) {
		this.workDisabilityId = workDisabilityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diagnosisId")
	public Diagnosis getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDisability", length = 10)
	public Date getStartDisability() {
		return this.startDisability;
	}

	public void setStartDisability(Date startDisability) {
		this.startDisability = startDisability;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDisability", length = 10)
	public Date getEndDisability() {
		return this.endDisability;
	}

	public void setEndDisability(Date endDisability) {
		this.endDisability = endDisability;
	}

	@Column(name = "reason", length = 65535)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "bedRest")
	public Boolean getBedRest() {
		return this.bedRest;
	}

	public void setBedRest(Boolean bedRest) {
		this.bedRest = bedRest;
	}

}
